export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          slug: string;
          job_prefix: string;
          job_sequence: number;
          plan: string;
          contact_email: string | null;
          contact_phone: string | null;
          address: string | null;
          logo_storage_path: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          job_prefix: string;
          job_sequence?: number;
          plan?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          address?: string | null;
          logo_storage_path?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          job_prefix?: string;
          job_sequence?: number;
          plan?: string;
          contact_email?: string | null;
          contact_phone?: string | null;
          address?: string | null;
          logo_storage_path?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      users: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          role: string;
          phone: string | null;
          address: string | null;
          is_emergency_contact: boolean;
          makesafe_available: boolean;
          can_send_to_insurer: boolean | null;
          can_edit_settings: boolean | null;
          can_approve_invoices: boolean | null;
          can_manage_scope_library: boolean | null;
          can_view_financials: boolean | null;
          created_at: string;
        };
        Insert: {
          id: string;
          tenant_id: string;
          name: string;
          role: string;
          phone?: string | null;
          address?: string | null;
          is_emergency_contact?: boolean;
          makesafe_available?: boolean;
          can_send_to_insurer?: boolean | null;
          can_edit_settings?: boolean | null;
          can_approve_invoices?: boolean | null;
          can_manage_scope_library?: boolean | null;
          can_view_financials?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          role?: string;
          phone?: string | null;
          address?: string | null;
          is_emergency_contact?: boolean;
          makesafe_available?: boolean;
          can_send_to_insurer?: boolean | null;
          can_edit_settings?: boolean | null;
          can_approve_invoices?: boolean | null;
          can_manage_scope_library?: boolean | null;
          can_view_financials?: boolean | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      clients: {
        Row: {
          id: string;
          tenant_id: string;
          client_type: string;
          parent_id: string | null;
          name: string;
          trading_name: string | null;
          abn: string | null;
          submission_email: string | null;
          contact_phone: string | null;
          address: string | null;
          kpi_contact_hours: number;
          kpi_booking_hours: number;
          kpi_visit_days: number;
          kpi_report_days: number;
          send_booking_confirmation: boolean;
          notes: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          client_type: string;
          parent_id?: string | null;
          name: string;
          trading_name?: string | null;
          abn?: string | null;
          submission_email?: string | null;
          contact_phone?: string | null;
          address?: string | null;
          kpi_contact_hours?: number;
          kpi_booking_hours?: number;
          kpi_visit_days?: number;
          kpi_report_days?: number;
          send_booking_confirmation?: boolean;
          notes?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          client_type?: string;
          parent_id?: string | null;
          name?: string;
          trading_name?: string | null;
          abn?: string | null;
          submission_email?: string | null;
          contact_phone?: string | null;
          address?: string | null;
          kpi_contact_hours?: number;
          kpi_booking_hours?: number;
          kpi_visit_days?: number;
          kpi_report_days?: number;
          send_booking_confirmation?: boolean;
          notes?: string | null;
          status?: string;
          created_at?: string;
        };
        Relationships: never[];
      };
      jobs: {
        Row: {
          id: string;
          tenant_id: string;
          job_number: string;
          claim_number: string | null;
          client_id: string | null;
          insurer: string | null;
          adjuster: string | null;
          property_address: string | null;
          insured_name: string | null;
          insured_phone: string | null;
          insured_email: string | null;
          additional_contacts: string | null;
          date_of_loss: string | null;
          loss_type: string | null;
          claim_description: string | null;
          special_instructions: string | null;
          sum_insured: number | null;
          excess: number | null;
          assigned_to: string | null;
          status: string;
          kpi_contact_due: string | null;
          kpi_booking_due: string | null;
          kpi_visit_due: string | null;
          kpi_report_due: string | null;
          kpi_contacted_at: string | null;
          kpi_booked_at: string | null;
          kpi_visited_at: string | null;
          kpi_reported_at: string | null;
          notes: string | null;
          automation_overrides: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_number: string;
          claim_number?: string | null;
          client_id?: string | null;
          insurer?: string | null;
          adjuster?: string | null;
          property_address?: string | null;
          insured_name?: string | null;
          insured_phone?: string | null;
          insured_email?: string | null;
          additional_contacts?: string | null;
          date_of_loss?: string | null;
          loss_type?: string | null;
          claim_description?: string | null;
          special_instructions?: string | null;
          sum_insured?: number | null;
          excess?: number | null;
          assigned_to?: string | null;
          status?: string;
          kpi_contact_due?: string | null;
          kpi_booking_due?: string | null;
          kpi_visit_due?: string | null;
          kpi_report_due?: string | null;
          kpi_contacted_at?: string | null;
          kpi_booked_at?: string | null;
          kpi_visited_at?: string | null;
          kpi_reported_at?: string | null;
          notes?: string | null;
          automation_overrides?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_number?: string;
          claim_number?: string | null;
          client_id?: string | null;
          insurer?: string | null;
          adjuster?: string | null;
          property_address?: string | null;
          insured_name?: string | null;
          insured_phone?: string | null;
          insured_email?: string | null;
          additional_contacts?: string | null;
          date_of_loss?: string | null;
          loss_type?: string | null;
          claim_description?: string | null;
          special_instructions?: string | null;
          sum_insured?: number | null;
          excess?: number | null;
          assigned_to?: string | null;
          status?: string;
          kpi_contact_due?: string | null;
          kpi_booking_due?: string | null;
          kpi_visit_due?: string | null;
          kpi_report_due?: string | null;
          kpi_contacted_at?: string | null;
          kpi_booked_at?: string | null;
          kpi_visited_at?: string | null;
          kpi_reported_at?: string | null;
          notes?: string | null;
          automation_overrides?: Json;
          created_at?: string;
        };
        Relationships: never[];
      };
      insurer_orders: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string | null;
          client_id: string | null;
          order_ref: string | null;
          status: string | null;
          claim_number: string;
          insurer: string | null;
          adjuster: string | null;
          wo_type: string | null;
          is_make_safe: boolean | null;
          property_address: string | null;
          insured_name: string | null;
          insured_phone: string | null;
          insured_email: string | null;
          additional_contacts: string | null;
          date_of_loss: string | null;
          loss_type: string | null;
          claim_description: string | null;
          special_instructions: string | null;
          sum_insured_building: number | null;
          excess_building: number | null;
          raw_email_link: string | null;
          parse_status: string | null;
          entry_method: string | null;
          notes: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id?: string | null;
          client_id?: string | null;
          order_ref?: string | null;
          status?: string | null;
          claim_number: string;
          insurer?: string | null;
          adjuster?: string | null;
          wo_type?: string | null;
          is_make_safe?: boolean | null;
          property_address?: string | null;
          insured_name?: string | null;
          insured_phone?: string | null;
          insured_email?: string | null;
          additional_contacts?: string | null;
          date_of_loss?: string | null;
          loss_type?: string | null;
          claim_description?: string | null;
          special_instructions?: string | null;
          sum_insured_building?: number | null;
          excess_building?: number | null;
          raw_email_link?: string | null;
          parse_status?: string | null;
          entry_method?: string | null;
          notes?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string | null;
          client_id?: string | null;
          order_ref?: string | null;
          status?: string | null;
          claim_number?: string;
          insurer?: string | null;
          adjuster?: string | null;
          wo_type?: string | null;
          is_make_safe?: boolean | null;
          property_address?: string | null;
          insured_name?: string | null;
          insured_phone?: string | null;
          insured_email?: string | null;
          additional_contacts?: string | null;
          date_of_loss?: string | null;
          loss_type?: string | null;
          claim_description?: string | null;
          special_instructions?: string | null;
          sum_insured_building?: number | null;
          excess_building?: number | null;
          raw_email_link?: string | null;
          parse_status?: string | null;
          entry_method?: string | null;
          notes?: string | null;
          created_at?: string | null;
        };
        Relationships: never[];
      };
      inspections: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          quote_id: string | null;
          report_id: string | null;
          inspection_ref: string | null;
          scheduled_date: string | null;
          scheduled_time: string | null;
          inspector_id: string | null;
          status: string;
          insured_notified: boolean;
          scheduling_sms_sent_at: string | null;
          scheduling_sms_response: string | null;
          booking_confirmed_at: string | null;
          access_notes: string | null;
          calendar_event_id: string | null;
          field_draft: Json | null;
          form_submitted_at: string | null;
          safety_confirmed_at: string | null;
          person_met: string | null;
          scope_status: string;
          report_status: string;
          photos_status: string;
          send_checklist: Json;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          quote_id?: string | null;
          report_id?: string | null;
          inspection_ref?: string | null;
          scheduled_date?: string | null;
          scheduled_time?: string | null;
          inspector_id?: string | null;
          status?: string;
          insured_notified?: boolean;
          scheduling_sms_sent_at?: string | null;
          scheduling_sms_response?: string | null;
          booking_confirmed_at?: string | null;
          access_notes?: string | null;
          calendar_event_id?: string | null;
          field_draft?: Json | null;
          form_submitted_at?: string | null;
          safety_confirmed_at?: string | null;
          person_met?: string | null;
          scope_status?: string;
          report_status?: string;
          photos_status?: string;
          send_checklist?: Json;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          quote_id?: string | null;
          report_id?: string | null;
          inspection_ref?: string | null;
          scheduled_date?: string | null;
          scheduled_time?: string | null;
          inspector_id?: string | null;
          status?: string;
          insured_notified?: boolean;
          scheduling_sms_sent_at?: string | null;
          scheduling_sms_response?: string | null;
          booking_confirmed_at?: string | null;
          access_notes?: string | null;
          calendar_event_id?: string | null;
          field_draft?: Json | null;
          form_submitted_at?: string | null;
          safety_confirmed_at?: string | null;
          person_met?: string | null;
          scope_status?: string;
          report_status?: string;
          photos_status?: string;
          send_checklist?: Json;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      safety_records: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          inspection_id: string | null;
          type: string | null;
          inspector_id: string | null;
          confirmed_at: string | null;
          date: string | null;
          status: string | null;
          signed_by: string | null;
          nearest_hospital: string | null;
          ppe_confirmed: boolean | null;
          hazards_noted: string | null;
          custom_notes: string | null;
          roof_access: boolean | null;
          structural_ok: boolean | null;
          asbestos_risk: boolean | null;
          lone_worker_checkin_active: boolean;
          lone_worker_checkin_interval_mins: number | null;
          signature_data: string | null;
          pdf_storage_path: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          inspection_id?: string | null;
          type?: string | null;
          inspector_id?: string | null;
          confirmed_at?: string | null;
          date?: string | null;
          status?: string | null;
          signed_by?: string | null;
          nearest_hospital?: string | null;
          ppe_confirmed?: boolean | null;
          hazards_noted?: string | null;
          custom_notes?: string | null;
          roof_access?: boolean | null;
          structural_ok?: boolean | null;
          asbestos_risk?: boolean | null;
          lone_worker_checkin_active?: boolean;
          lone_worker_checkin_interval_mins?: number | null;
          signature_data?: string | null;
          pdf_storage_path?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          inspection_id?: string | null;
          type?: string | null;
          inspector_id?: string | null;
          confirmed_at?: string | null;
          date?: string | null;
          status?: string | null;
          signed_by?: string | null;
          nearest_hospital?: string | null;
          ppe_confirmed?: boolean | null;
          hazards_noted?: string | null;
          custom_notes?: string | null;
          roof_access?: boolean | null;
          structural_ok?: boolean | null;
          asbestos_risk?: boolean | null;
          lone_worker_checkin_active?: boolean;
          lone_worker_checkin_interval_mins?: number | null;
          signature_data?: string | null;
          pdf_storage_path?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      reports: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          inspection_id: string | null;
          quote_id: string | null;
          parent_report_id: string | null;
          report_ref: string | null;
          version: number;
          is_locked: boolean;
          report_type: string;
          status: string;
          attendance_date: string | null;
          attendance_time: string | null;
          person_met: string | null;
          property_address: string | null;
          insured_name: string | null;
          claim_number: string | null;
          loss_type: string | null;
          assessor_name: string | null;
          property_description: string | null;
          incident_description: string | null;
          cause_of_damage: string | null;
          how_damage_occurred: string | null;
          resulting_damage: string | null;
          conclusion: string | null;
          pre_existing_conditions: string | null;
          maintenance_notes: string | null;
          raw_report_dump: string | null;
          damage_template: string | null;
          damage_template_saved: boolean;
          type_specific_fields: Json;
          doc_storage_path: string | null;
          pdf_storage_path: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
          delete_reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          inspection_id?: string | null;
          quote_id?: string | null;
          parent_report_id?: string | null;
          report_ref?: string | null;
          version?: number;
          is_locked?: boolean;
          report_type: string;
          status?: string;
          attendance_date?: string | null;
          attendance_time?: string | null;
          person_met?: string | null;
          property_address?: string | null;
          insured_name?: string | null;
          claim_number?: string | null;
          loss_type?: string | null;
          assessor_name?: string | null;
          property_description?: string | null;
          incident_description?: string | null;
          cause_of_damage?: string | null;
          how_damage_occurred?: string | null;
          resulting_damage?: string | null;
          conclusion?: string | null;
          pre_existing_conditions?: string | null;
          maintenance_notes?: string | null;
          raw_report_dump?: string | null;
          damage_template?: string | null;
          damage_template_saved?: boolean;
          type_specific_fields?: Json;
          doc_storage_path?: string | null;
          pdf_storage_path?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
          delete_reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          inspection_id?: string | null;
          quote_id?: string | null;
          parent_report_id?: string | null;
          report_ref?: string | null;
          version?: number;
          is_locked?: boolean;
          report_type?: string;
          status?: string;
          attendance_date?: string | null;
          attendance_time?: string | null;
          person_met?: string | null;
          property_address?: string | null;
          insured_name?: string | null;
          claim_number?: string | null;
          loss_type?: string | null;
          assessor_name?: string | null;
          property_description?: string | null;
          incident_description?: string | null;
          cause_of_damage?: string | null;
          how_damage_occurred?: string | null;
          resulting_damage?: string | null;
          conclusion?: string | null;
          pre_existing_conditions?: string | null;
          maintenance_notes?: string | null;
          raw_report_dump?: string | null;
          damage_template?: string | null;
          damage_template_saved?: boolean;
          type_specific_fields?: Json;
          doc_storage_path?: string | null;
          pdf_storage_path?: string | null;
          deleted_at?: string | null;
          deleted_by?: string | null;
          delete_reason?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      quotes: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          inspection_id: string | null;
          report_id: string | null;
          parent_quote_id: string | null;
          quote_ref: string | null;
          quote_type: string | null;
          version: number;
          is_active_version: boolean;
          is_locked: boolean;
          status: string;
          approved_amount: number | null;
          approval_notes: string | null;
          raw_scope_notes: string | null;
          total_amount: number | null;
          markup_pct: number;
          gst_pct: number;
          doc_storage_path: string | null;
          pdf_storage_path: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          inspection_id?: string | null;
          report_id?: string | null;
          parent_quote_id?: string | null;
          quote_ref?: string | null;
          quote_type?: string | null;
          version?: number;
          is_active_version?: boolean;
          is_locked?: boolean;
          status?: string;
          approved_amount?: number | null;
          approval_notes?: string | null;
          raw_scope_notes?: string | null;
          total_amount?: number | null;
          markup_pct?: number;
          gst_pct?: number;
          doc_storage_path?: string | null;
          pdf_storage_path?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          inspection_id?: string | null;
          report_id?: string | null;
          parent_quote_id?: string | null;
          quote_ref?: string | null;
          quote_type?: string | null;
          version?: number;
          is_active_version?: boolean;
          is_locked?: boolean;
          status?: string;
          approved_amount?: number | null;
          approval_notes?: string | null;
          raw_scope_notes?: string | null;
          total_amount?: number | null;
          markup_pct?: number;
          gst_pct?: number;
          doc_storage_path?: string | null;
          pdf_storage_path?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      scope_items: {
        Row: {
          id: string;
          tenant_id: string;
          quote_id: string;
          scope_library_id: string | null;
          room: string | null;
          room_length: number | null;
          room_width: number | null;
          room_height: number | null;
          trade: string | null;
          keyword: string | null;
          item_description: string | null;
          unit: string | null;
          qty: number | null;
          rate_labour: number | null;
          rate_materials: number | null;
          rate_total: number | null;
          line_total: number | null;
          split_type: string | null;
          approval_status: string;
          is_custom: boolean;
          library_writeback_approved: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          quote_id: string;
          scope_library_id?: string | null;
          room?: string | null;
          room_length?: number | null;
          room_width?: number | null;
          room_height?: number | null;
          trade?: string | null;
          keyword?: string | null;
          item_description?: string | null;
          unit?: string | null;
          qty?: number | null;
          rate_labour?: number | null;
          rate_materials?: number | null;
          rate_total?: number | null;
          line_total?: number | null;
          split_type?: string | null;
          approval_status?: string;
          is_custom?: boolean;
          library_writeback_approved?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          quote_id?: string;
          scope_library_id?: string | null;
          room?: string | null;
          room_length?: number | null;
          room_width?: number | null;
          room_height?: number | null;
          trade?: string | null;
          keyword?: string | null;
          item_description?: string | null;
          unit?: string | null;
          qty?: number | null;
          rate_labour?: number | null;
          rate_materials?: number | null;
          rate_total?: number | null;
          line_total?: number | null;
          split_type?: string | null;
          approval_status?: string;
          is_custom?: boolean;
          library_writeback_approved?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: never[];
      };
      scope_library: {
        Row: {
          id: string;
          tenant_id: string;
          insurer_specific: string | null;
          pair_id: string | null;
          split_type: string | null;
          trade: string | null;
          keyword: string | null;
          item_description: string | null;
          unit: string | null;
          labour_rate_per_hour: number | null;
          labour_per_unit: number | null;
          materials_per_unit: number | null;
          total_per_unit: number | null;
          // v3.0 scheduling fields
          estimated_hours: number | null;
          has_lag: boolean;
          lag_days: number | null;
          lag_description: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          insurer_specific?: string | null;
          pair_id?: string | null;
          split_type?: string | null;
          trade?: string | null;
          keyword?: string | null;
          item_description?: string | null;
          unit?: string | null;
          labour_rate_per_hour?: number | null;
          labour_per_unit?: number | null;
          materials_per_unit?: number | null;
          total_per_unit?: number | null;
          estimated_hours?: number | null;
          has_lag?: boolean;
          lag_days?: number | null;
          lag_description?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          insurer_specific?: string | null;
          pair_id?: string | null;
          split_type?: string | null;
          trade?: string | null;
          keyword?: string | null;
          item_description?: string | null;
          unit?: string | null;
          labour_rate_per_hour?: number | null;
          labour_per_unit?: number | null;
          materials_per_unit?: number | null;
          total_per_unit?: number | null;
          estimated_hours?: number | null;
          has_lag?: boolean;
          lag_days?: number | null;
          lag_description?: string | null;
          updated_at?: string;
        };
        Relationships: never[];
      };
      report_templates: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          report_type: string;
          loss_types: string[] | null;
          use_count: number;
          last_used_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          report_type: string;
          loss_types?: string[] | null;
          use_count?: number;
          last_used_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          report_type?: string;
          loss_types?: string[] | null;
          use_count?: number;
          last_used_at?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      trades: {
        Row: {
          id: string;
          tenant_id: string;
          primary_trade: string | null;
          trade_code: string | null;
          business_name: string | null;
          entity_name: string | null;
          abn: string | null;
          primary_contact: string | null;
          address: string | null;
          // v3.0 fields
          lat: number | null;
          lng: number | null;
          contact_email: string | null;
          contact_mobile: string | null;
          contact_office: string | null;
          can_do_make_safe: boolean;
          makesafe_priority: number | null;
          can_do_reports: boolean;
          availability: string;
          priority_rank: number;
          gary_opt_out: boolean;
          gary_contact_preference: string | null;
          gary_notes: string | null;
          status: string;
          status_note: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          primary_trade?: string | null;
          trade_code?: string | null;
          business_name?: string | null;
          entity_name?: string | null;
          abn?: string | null;
          primary_contact?: string | null;
          address?: string | null;
          lat?: number | null;
          lng?: number | null;
          contact_email?: string | null;
          contact_mobile?: string | null;
          contact_office?: string | null;
          can_do_make_safe?: boolean;
          makesafe_priority?: number | null;
          can_do_reports?: boolean;
          availability?: string;
          priority_rank?: number;
          gary_opt_out?: boolean;
          gary_contact_preference?: string | null;
          gary_notes?: string | null;
          status?: string;
          status_note?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          primary_trade?: string | null;
          trade_code?: string | null;
          business_name?: string | null;
          entity_name?: string | null;
          abn?: string | null;
          primary_contact?: string | null;
          address?: string | null;
          lat?: number | null;
          lng?: number | null;
          contact_email?: string | null;
          contact_mobile?: string | null;
          contact_office?: string | null;
          can_do_make_safe?: boolean;
          makesafe_priority?: number | null;
          can_do_reports?: boolean;
          availability?: string;
          priority_rank?: number;
          gary_opt_out?: boolean;
          gary_contact_preference?: string | null;
          gary_notes?: string | null;
          status?: string;
          status_note?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      // v3.0: work_orders — scheduled_date REMOVED; new scheduling columns added
      work_orders: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          quote_id: string | null;
          trade_id: string | null;
          report_id: string | null;
          blueprint_id: string | null;
          work_type: string | null;
          status: string;
          sequence_order: number | null;
          is_concurrent: boolean;
          predecessor_work_order_id: string | null;
          estimated_hours: number | null;
          total_visits: number;
          current_visit: number;
          proximity_range: string | null;
          gary_state: string;
          scope_summary: string | null;
          trade_cost: number | null;
          charge_out_amount: number | null;
          agreed_amount: number | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          quote_id?: string | null;
          trade_id?: string | null;
          report_id?: string | null;
          blueprint_id?: string | null;
          work_type?: string | null;
          status?: string;
          sequence_order?: number | null;
          is_concurrent?: boolean;
          predecessor_work_order_id?: string | null;
          estimated_hours?: number | null;
          total_visits?: number;
          current_visit?: number;
          proximity_range?: string | null;
          gary_state?: string;
          scope_summary?: string | null;
          trade_cost?: number | null;
          charge_out_amount?: number | null;
          agreed_amount?: number | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          quote_id?: string | null;
          trade_id?: string | null;
          report_id?: string | null;
          blueprint_id?: string | null;
          work_type?: string | null;
          status?: string;
          sequence_order?: number | null;
          is_concurrent?: boolean;
          predecessor_work_order_id?: string | null;
          estimated_hours?: number | null;
          total_visits?: number;
          current_visit?: number;
          proximity_range?: string | null;
          gary_state?: string;
          scope_summary?: string | null;
          trade_cost?: number | null;
          charge_out_amount?: number | null;
          agreed_amount?: number | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      // v3.0 new table
      work_order_visits: {
        Row: {
          id: string;
          tenant_id: string;
          work_order_id: string;
          job_id: string;
          visit_number: number;
          estimated_hours: number | null;
          scheduled_date: string | null;
          scheduled_end_date: string | null;
          confirmed_date: string | null;
          status: string;
          lag_days_after: number;
          lag_description: string | null;
          gary_triggered_at: string | null;
          gary_return_trigger_at: string | null;
          trade_confirmed_at: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          work_order_id: string;
          job_id: string;
          visit_number: number;
          estimated_hours?: number | null;
          scheduled_date?: string | null;
          scheduled_end_date?: string | null;
          confirmed_date?: string | null;
          status?: string;
          lag_days_after?: number;
          lag_description?: string | null;
          gary_triggered_at?: string | null;
          gary_return_trigger_at?: string | null;
          trade_confirmed_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          work_order_id?: string;
          job_id?: string;
          visit_number?: number;
          estimated_hours?: number | null;
          scheduled_date?: string | null;
          scheduled_end_date?: string | null;
          confirmed_date?: string | null;
          status?: string;
          lag_days_after?: number;
          lag_description?: string | null;
          gary_triggered_at?: string | null;
          gary_return_trigger_at?: string | null;
          trade_confirmed_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      // v3.0 new table
      job_schedule_blueprints: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          status: string;
          draft_data: Json | null;
          confirmed_by: string | null;
          confirmed_at: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          status?: string;
          draft_data?: Json | null;
          confirmed_by?: string | null;
          confirmed_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          status?: string;
          draft_data?: Json | null;
          confirmed_by?: string | null;
          confirmed_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      // v3.0 new table
      trade_type_sequence: {
        Row: {
          id: string;
          tenant_id: string;
          trade_type: string;
          typical_sequence_order: number | null;
          typical_visit_count: number;
          notes: string | null;
          updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          trade_type: string;
          typical_sequence_order?: number | null;
          typical_visit_count?: number;
          notes?: string | null;
          updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          trade_type?: string;
          typical_sequence_order?: number | null;
          typical_visit_count?: number;
          notes?: string | null;
          updated_at?: string;
          created_at?: string;
        };
        Relationships: never[];
      };
      communications: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string | null;
          inspection_id: string | null;
          work_order_id: string | null;
          type: string;
          direction: string | null;
          contact_type: string | null;
          contact_name: string | null;
          contact_detail: string | null;
          subject: string | null;
          content: string | null;
          attachments: Json;
          ai_extracted_notes: string | null;
          requires_action: boolean;
          action_queue_id: string | null;
          persona: string | null;
          parse_confidence: string | null;
          linked_to: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id?: string | null;
          inspection_id?: string | null;
          work_order_id?: string | null;
          type: string;
          direction?: string | null;
          contact_type?: string | null;
          contact_name?: string | null;
          contact_detail?: string | null;
          subject?: string | null;
          content?: string | null;
          attachments?: Json;
          ai_extracted_notes?: string | null;
          requires_action?: boolean;
          action_queue_id?: string | null;
          persona?: string | null;
          parse_confidence?: string | null;
          linked_to?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string | null;
          inspection_id?: string | null;
          work_order_id?: string | null;
          type?: string;
          direction?: string | null;
          contact_type?: string | null;
          contact_name?: string | null;
          contact_detail?: string | null;
          subject?: string | null;
          content?: string | null;
          attachments?: Json;
          ai_extracted_notes?: string | null;
          requires_action?: boolean;
          action_queue_id?: string | null;
          persona?: string | null;
          parse_confidence?: string | null;
          linked_to?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      photos: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          inspection_id: string | null;
          storage_path: string;
          label: string | null;
          report_code: string | null;
          sequence_number: number | null;
          file_name: string | null;
          mime_type: string | null;
          size_bytes: number | null;
          uploaded_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          inspection_id?: string | null;
          storage_path: string;
          label?: string | null;
          report_code?: string | null;
          sequence_number?: number | null;
          file_name?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          uploaded_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          inspection_id?: string | null;
          storage_path?: string;
          label?: string | null;
          report_code?: string | null;
          sequence_number?: number | null;
          file_name?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          uploaded_at?: string;
        };
        Relationships: never[];
      };
      invoices: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          work_order_id: string | null;
          report_id: string | null;
          invoice_ref: string | null;
          invoice_type: string;
          direction: string;
          trade_id: string | null;
          trade_invoice_number: string | null;
          trade_invoice_date: string | null;
          trade_pdf_storage_path: string | null;
          trade_abn: string | null;
          amount_ex_gst: number | null;
          gst: number | null;
          amount_inc_gst: number | null;
          status: string;
          external_status: string | null;
          parse_status: string | null;
          issued_date: string | null;
          paid_date: string | null;
          xero_invoice_id: string | null;
          xero_sync_status: string;
          xero_sync_error: string | null;
          xero_last_synced_at: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          work_order_id?: string | null;
          report_id?: string | null;
          invoice_ref?: string | null;
          invoice_type: string;
          direction: string;
          trade_id?: string | null;
          trade_invoice_number?: string | null;
          trade_invoice_date?: string | null;
          trade_pdf_storage_path?: string | null;
          trade_abn?: string | null;
          amount_ex_gst?: number | null;
          gst?: number | null;
          amount_inc_gst?: number | null;
          status?: string;
          external_status?: string | null;
          parse_status?: string | null;
          issued_date?: string | null;
          paid_date?: string | null;
          xero_invoice_id?: string | null;
          xero_sync_status?: string;
          xero_sync_error?: string | null;
          xero_last_synced_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          work_order_id?: string | null;
          report_id?: string | null;
          invoice_ref?: string | null;
          invoice_type?: string;
          direction?: string;
          trade_id?: string | null;
          trade_invoice_number?: string | null;
          trade_invoice_date?: string | null;
          trade_pdf_storage_path?: string | null;
          trade_abn?: string | null;
          amount_ex_gst?: number | null;
          gst?: number | null;
          amount_inc_gst?: number | null;
          status?: string;
          external_status?: string | null;
          parse_status?: string | null;
          issued_date?: string | null;
          paid_date?: string | null;
          xero_invoice_id?: string | null;
          xero_sync_status?: string;
          xero_sync_error?: string | null;
          xero_last_synced_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      email_templates: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          send_type: string;
          client_id: string | null;
          subject_template: string | null;
          body_template: string | null;
          is_default: boolean;
          updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          send_type: string;
          client_id?: string | null;
          subject_template?: string | null;
          body_template?: string | null;
          is_default?: boolean;
          updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          send_type?: string;
          client_id?: string | null;
          subject_template?: string | null;
          body_template?: string | null;
          is_default?: boolean;
          updated_at?: string;
          created_at?: string;
        };
        Relationships: never[];
      };
      automation_config: {
        Row: {
          id: string;
          tenant_id: string;
          key: string;
          value: string;
          description: string | null;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          key: string;
          value: string;
          description?: string | null;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          key?: string;
          value?: string;
          description?: string | null;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: never[];
      };
      rate_config: {
        Row: {
          id: string;
          tenant_id: string;
          report_type: string;
          min_charge: number | null;
          standard_charge: number | null;
          margin_pct: number | null;
          gst_pct: number;
          notes: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          report_type: string;
          min_charge?: number | null;
          standard_charge?: number | null;
          margin_pct?: number | null;
          gst_pct?: number;
          notes?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          report_type?: string;
          min_charge?: number | null;
          standard_charge?: number | null;
          margin_pct?: number | null;
          gst_pct?: number;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: never[];
      };
      portal_tokens: {
        Row: {
          id: string;
          tenant_id: string;
          work_order_id: string;
          token: string;
          is_active: boolean;
          expires_at: string | null;
          revoked_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          work_order_id: string;
          token: string;
          is_active?: boolean;
          expires_at?: string | null;
          revoked_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          work_order_id?: string;
          token?: string;
          is_active?: boolean;
          expires_at?: string | null;
          revoked_at?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      job_flags: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          user_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          user_id?: string;
          created_at?: string;
        };
        Relationships: never[];
      };
      job_notes: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          content: string;
          is_pinned: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          content: string;
          is_pinned?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          content?: string;
          is_pinned?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: never[];
      };
      scope_library_history: {
        Row: {
          id: string;
          tenant_id: string;
          scope_library_id: string;
          snapshot: Json;
          changed_by: string | null;
          changed_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          scope_library_id: string;
          snapshot: Json;
          changed_by?: string | null;
          changed_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          scope_library_id?: string;
          snapshot?: Json;
          changed_by?: string | null;
          changed_at?: string;
        };
        Relationships: never[];
      };
      audit_log: {
        Row: {
          id: string;
          tenant_id: string;
          actor_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string;
          before_state: Json | null;
          after_state: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          actor_id?: string | null;
          action: string;
          entity_type: string;
          entity_id: string;
          before_state?: Json | null;
          after_state?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          actor_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string;
          before_state?: Json | null;
          after_state?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
      prompts: {
        Row: {
          id: string;
          tenant_id: string;
          key: string;
          name: string;
          category: string;
          report_type: string | null;
          system_prompt: string;
          previous_prompt: string | null;
          notes: string | null;
          updated_by: string | null;
          updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          key: string;
          name: string;
          category: string;
          report_type?: string | null;
          system_prompt: string;
          previous_prompt?: string | null;
          notes?: string | null;
          updated_by?: string | null;
          updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          key?: string;
          name?: string;
          category?: string;
          report_type?: string | null;
          system_prompt?: string;
          previous_prompt?: string | null;
          notes?: string | null;
          updated_by?: string | null;
          updated_at?: string;
          created_at?: string;
        };
        Relationships: never[];
      };
      action_queue: {
        Row: {
          id: string;
          tenant_id: string;
          job_id: string;
          rule_key: string;
          title: string;
          description: string | null;
          ai_draft: Json | null;
          status: string;
          priority: number;
          snoozed_until: string | null;
          confirmed_by: string | null;
          confirmed_at: string | null;
          error_log: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          job_id: string;
          rule_key: string;
          title: string;
          description?: string | null;
          ai_draft?: Json | null;
          status?: string;
          priority?: number;
          snoozed_until?: string | null;
          confirmed_by?: string | null;
          confirmed_at?: string | null;
          error_log?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          job_id?: string;
          rule_key?: string;
          title?: string;
          description?: string | null;
          ai_draft?: Json | null;
          status?: string;
          priority?: number;
          snoozed_until?: string | null;
          confirmed_by?: string | null;
          confirmed_at?: string | null;
          error_log?: string | null;
          created_at?: string;
        };
        Relationships: never[];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
